//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlay.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicPlay.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorite.
        /// </summary>
        public static string Add_To_Favorite {
            get {
                return ResourceManager.GetString("Add_To_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Playlist.
        /// </summary>
        public static string Add_To_Playlist {
            get {
                return ResourceManager.GetString("Add_To_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string Add_To_Queue {
            get {
                return ResourceManager.GetString("Add_To_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist.
        /// </summary>
        public static string Album_Artist {
            get {
                return ResourceManager.GetString("Album_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album-Artists.
        /// </summary>
        public static string Album_Artists {
            get {
                return ResourceManager.GetString("Album_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Genre.
        /// </summary>
        public static string Album_Genre {
            get {
                return ResourceManager.GetString("Album_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Cover.
        /// </summary>
        public static string AlbumCover {
            get {
                return ResourceManager.GetString("AlbumCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums_View {
            get {
                return ResourceManager.GetString("Albums_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all your albums..
        /// </summary>
        public static string Albums_View_Dscpt {
            get {
                return ResourceManager.GetString("Albums_View_Dscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied.
        /// </summary>
        public static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string Artists_View {
            get {
                return ResourceManager.GetString("Artists_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all your artists..
        /// </summary>
        public static string Artists_View_Dscpt {
            get {
                return ResourceManager.GetString("Artists_View_Dscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork (Track Cover).
        /// </summary>
        public static string Artwork {
            get {
                return ResourceManager.GetString("Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artwork has been changed for .
        /// </summary>
        public static string Artwork_Changed_Msg {
            get {
                return ResourceManager.GetString("Artwork_Changed_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Artwork has been deleted for.
        /// </summary>
        public static string ArtworkDeletedMsg {
            get {
                return ResourceManager.GetString("ArtworkDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending Year.
        /// </summary>
        public static string Ascending_Year {
            get {
                return ResourceManager.GetString("Ascending_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Bitrate.
        /// </summary>
        public static string Audio_Bitrate {
            get {
                return ResourceManager.GetString("Audio_Bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Channels.
        /// </summary>
        public static string Audio_Channels {
            get {
                return ResourceManager.GetString("Audio_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Sample Rate.
        /// </summary>
        public static string Audio_Sample_Rate {
            get {
                return ResourceManager.GetString("Audio_Sample_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string AutoCover {
            get {
                return ResourceManager.GetString("AutoCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits per Sample.
        /// </summary>
        public static string Bits_per_Sample {
            get {
                return ResourceManager.GetString("Bits_per_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Artwork.
        /// </summary>
        public static string Change_Artwork {
            get {
                return ResourceManager.GetString("Change_Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Cover.
        /// </summary>
        public static string Change_Cover {
            get {
                return ResourceManager.GetString("Change_Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Folder.
        /// </summary>
        public static string ChangeDirectory {
            get {
                return ResourceManager.GetString("ChangeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Cantonese).
        /// </summary>
        public static string Chinese_Cantonese_Lang {
            get {
                return ResourceManager.GetString("Chinese_Cantonese_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Mandorin).
        /// </summary>
        public static string Chinese_Mandarin_Lang {
            get {
                return ResourceManager.GetString("Chinese_Mandarin_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cirlce with Bars.
        /// </summary>
        public static string CircledBar {
            get {
                return ResourceManager.GetString("CircledBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Graph.
        /// </summary>
        public static string CircledGraph {
            get {
                return ResourceManager.GetString("CircledGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cirlce with Points.
        /// </summary>
        public static string CircledPoints {
            get {
                return ResourceManager.GetString("CircledPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Database.
        /// </summary>
        public static string ClearDatabase {
            get {
                return ResourceManager.GetString("ClearDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec.
        /// </summary>
        public static string Codec {
            get {
                return ResourceManager.GetString("Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composers.
        /// </summary>
        public static string Composers {
            get {
                return ResourceManager.GetString("Composers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyRight.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cover has been changed for.
        /// </summary>
        public static string Cover_Changed_Msg {
            get {
                return ResourceManager.GetString("Cover_Changed_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cover has been deleted for.
        /// </summary>
        public static string CoverDeletedMsg {
            get {
                return ResourceManager.GetString("CoverDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Playlist.
        /// </summary>
        public static string Create_Playlist {
            get {
                return ResourceManager.GetString("Create_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Folder: .
        /// </summary>
        public static string CurrentDirectory {
            get {
                return ResourceManager.GetString("CurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Dark Theme.
        /// </summary>
        public static string Dark_Theme {
            get {
                return ResourceManager.GetString("Dark_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataBase has been deleted..
        /// </summary>
        public static string DataBase_Cleared_Msg {
            get {
                return ResourceManager.GetString("DataBase_Cleared_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending Year.
        /// </summary>
        public static string Descending_Year {
            get {
                return ResourceManager.GetString("Descending_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English_Lang {
            get {
                return ResourceManager.GetString("English_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current file is corrupted and cannot be played..
        /// </summary>
        public static string Error_Corrupted_File {
            get {
                return ResourceManager.GetString("Error_Corrupted_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection..
        /// </summary>
        public static string Error_No_Connection {
            get {
                return ResourceManager.GetString("Error_No_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough data to create a radio yet. Listen to more tracks and try again!.
        /// </summary>
        public static string Error_Not_Enough_Data_Radio {
            get {
                return ResourceManager.GetString("Error_Not_Enough_Data_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraLarge.
        /// </summary>
        public static string ExtraLarge {
            get {
                return ResourceManager.GetString("ExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraThin.
        /// </summary>
        public static string ExtraThin {
            get {
                return ResourceManager.GetString("ExtraThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of your Favorites tracks in one place!.
        /// </summary>
        public static string Favorite_Dscpt {
            get {
                return ResourceManager.GetString("Favorite_Dscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string File_Path {
            get {
                return ResourceManager.GetString("File_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Properties.
        /// </summary>
        public static string File_Properties {
            get {
                return ResourceManager.GetString("File_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename, Sample Rate,  Audio Bitrate....
        /// </summary>
        public static string File_Properties_Dscpt {
            get {
                return ResourceManager.GetString("File_Properties_Dscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Time Playing!.
        /// </summary>
        public static string Fisrt_Time_Playing {
            get {
                return ResourceManager.GetString("Fisrt_Time_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French_Lang {
            get {
                return ResourceManager.GetString("French_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General_Setting {
            get {
                return ResourceManager.GetString("General_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German_Lang {
            get {
                return ResourceManager.GetString("German_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening.
        /// </summary>
        public static string Good_Evening {
            get {
                return ResourceManager.GetString("Good_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning.
        /// </summary>
        public static string Good_Morning {
            get {
                return ResourceManager.GetString("Good_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient.
        /// </summary>
        public static string Gradient {
            get {
                return ResourceManager.GetString("Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been added to.
        /// </summary>
        public static string Has_been_Added_To {
            get {
                return ResourceManager.GetString("Has_been_Added_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been changed to.
        /// </summary>
        public static string Has_Been_Changed_To {
            get {
                return ResourceManager.GetString("Has_Been_Changed_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been created..
        /// </summary>
        public static string Has_Been_Created {
            get {
                return ResourceManager.GetString("Has_Been_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been deleted..
        /// </summary>
        public static string Has_Been_Deleted {
            get {
                return ResourceManager.GetString("Has_Been_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been removed from.
        /// </summary>
        public static string Has_Been_Removed_From {
            get {
                return ResourceManager.GetString("Has_Been_Removed_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been updated..
        /// </summary>
        public static string Has_Been_Updated {
            get {
                return ResourceManager.GetString("Has_Been_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have been added to .
        /// </summary>
        public static string Have_been_added_to {
            get {
                return ResourceManager.GetString("Have_been_added_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_View {
            get {
                return ResourceManager.GetString("Home_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a folder to import your library or add new tracks to it..
        /// </summary>
        public static string Import_Directory {
            get {
                return ResourceManager.GetString("Import_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for Artists....
        /// </summary>
        public static string ImportMsg1 {
            get {
                return ResourceManager.GetString("ImportMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Albums and Tracks....
        /// </summary>
        public static string ImportMsg2 {
            get {
                return ResourceManager.GetString("ImportMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Artists data....
        /// </summary>
        public static string ImportMsg3 {
            get {
                return ResourceManager.GetString("ImportMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese_Lang {
            get {
                return ResourceManager.GetString("Japanese_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Korean_Lang {
            get {
                return ResourceManager.GetString("Korean_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language has been changed to.
        /// </summary>
        public static string Language_Changed_Msg {
            get {
                return ResourceManager.GetString("Language_Changed_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_Setting {
            get {
                return ResourceManager.GetString("Language_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Played.
        /// </summary>
        public static string Last_Played {
            get {
                return ResourceManager.GetString("Last_Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your playback history (up to 100 tracks)..
        /// </summary>
        public static string Last_Played_Dscpt {
            get {
                return ResourceManager.GetString("Last_Played_Dscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Light Theme.
        /// </summary>
        public static string Light_Theme {
            get {
                return ResourceManager.GetString("Light_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downward Tap Points.
        /// </summary>
        public static string LinearDownTapPoint {
            get {
                return ResourceManager.GetString("LinearDownTapPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downward Bars.
        /// </summary>
        public static string LinearDownwardBar {
            get {
                return ResourceManager.GetString("LinearDownwardBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downward Graph.
        /// </summary>
        public static string LinearDownwardGraph {
            get {
                return ResourceManager.GetString("LinearDownwardGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downward Points.
        /// </summary>
        public static string LinearDownwardPoints {
            get {
                return ResourceManager.GetString("LinearDownwardPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirrored Bars.
        /// </summary>
        public static string LinearMirroredBar {
            get {
                return ResourceManager.GetString("LinearMirroredBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirrored Graph.
        /// </summary>
        public static string LinearMirroredGraph {
            get {
                return ResourceManager.GetString("LinearMirroredGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirrored Points.
        /// </summary>
        public static string LinearMirroredPoints {
            get {
                return ResourceManager.GetString("LinearMirroredPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upward Tap Points.
        /// </summary>
        public static string LinearUpTapPoint {
            get {
                return ResourceManager.GetString("LinearUpTapPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upward Bars.
        /// </summary>
        public static string LinearUpwardBar {
            get {
                return ResourceManager.GetString("LinearUpwardBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upward Graph.
        /// </summary>
        public static string LinearUpwardGraph {
            get {
                return ResourceManager.GetString("LinearUpwardGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upward Points.
        /// </summary>
        public static string LinearUpwardPoints {
            get {
                return ResourceManager.GetString("LinearUpwardPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string Lyrics_View {
            get {
                return ResourceManager.GetString("Lyrics_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Informations.
        /// </summary>
        public static string Main_Informations {
            get {
                return ResourceManager.GetString("Main_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title, Album, Performer, Genre, Copyright....
        /// </summary>
        public static string Main_Informations_Dscpt {
            get {
                return ResourceManager.GetString("Main_Informations_Dscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Played.
        /// </summary>
        public static string Most_Played {
            get {
                return ResourceManager.GetString("Most_Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Most Played Traks (Top 50)..
        /// </summary>
        public static string Most_Played_Dscpt {
            get {
                return ResourceManager.GetString("Most_Played_Dscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Albums.
        /// </summary>
        public static string MyAlbums {
            get {
                return ResourceManager.GetString("MyAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Artists.
        /// </summary>
        public static string MyArtists {
            get {
                return ResourceManager.GetString("MyArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Playlists.
        /// </summary>
        public static string MyPlaylists {
            get {
                return ResourceManager.GetString("MyPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Played.
        /// </summary>
        public static string Never_Played {
            get {
                return ResourceManager.GetString("Never_Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Albums Found.
        /// </summary>
        public static string No_Albums_Found {
            get {
                return ResourceManager.GetString("No_Albums_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Artists Found.
        /// </summary>
        public static string No_Artists_Found {
            get {
                return ResourceManager.GetString("No_Artists_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Access.
        /// </summary>
        public static string No_Connection {
            get {
                return ResourceManager.GetString("No_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No History.
        /// </summary>
        public static string No_History {
            get {
                return ResourceManager.GetString("No_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lyrics found.
        /// </summary>
        public static string No_Lyrics_Found {
            get {
                return ResourceManager.GetString("No_Lyrics_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Playlists Found.
        /// </summary>
        public static string No_Playlists_Found {
            get {
                return ResourceManager.GetString("No_Playlists_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        public static string Now_Playing_View {
            get {
                return ResourceManager.GetString("Now_Playing_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity (%).
        /// </summary>
        public static string Opcaity {
            get {
                return ResourceManager.GetString("Opcaity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance might be affected.
        /// </summary>
        public static string Performance_Warning {
            get {
                return ResourceManager.GetString("Performance_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performer.
        /// </summary>
        public static string Performer {
            get {
                return ResourceManager.GetString("Performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performers.
        /// </summary>
        public static string Performers {
            get {
                return ResourceManager.GetString("Performers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be permanently deleted..
        /// </summary>
        public static string PermanentlyDeletedWarning {
            get {
                return ResourceManager.GetString("PermanentlyDeletedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play from a URL.
        /// </summary>
        public static string Play_From_URL {
            get {
                return ResourceManager.GetString("Play_From_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Next.
        /// </summary>
        public static string Play_Next {
            get {
                return ResourceManager.GetString("Play_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Record of.
        /// </summary>
        public static string Playback_history_of {
            get {
                return ResourceManager.GetString("Playback_history_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Count.
        /// </summary>
        public static string PlayCount {
            get {
                return ResourceManager.GetString("PlayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing from .
        /// </summary>
        public static string PlayingFrom {
            get {
                return ResourceManager.GetString("PlayingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Cover (optional).
        /// </summary>
        public static string Playlist_Cover {
            get {
                return ResourceManager.GetString("Playlist_Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new playlist has been created: .
        /// </summary>
        public static string Playlist_Created_Msg {
            get {
                return ResourceManager.GetString("Playlist_Created_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Description (optional).
        /// </summary>
        public static string Playlist_Description {
            get {
                return ResourceManager.GetString("Playlist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Name.
        /// </summary>
        public static string Playlist_Name {
            get {
                return ResourceManager.GetString("Playlist_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Playlists_View {
            get {
                return ResourceManager.GetString("Playlists_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue_View {
            get {
                return ResourceManager.GetString("Queue_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Covers Display Options.
        /// </summary>
        public static string QueueCover_Settings {
            get {
                return ResourceManager.GetString("QueueCover_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radios for You.
        /// </summary>
        public static string Radio_Station_For_You {
            get {
                return ResourceManager.GetString("Radio_Station_For_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Played Albums.
        /// </summary>
        public static string Recently_Played_Albums {
            get {
                return ResourceManager.GetString("Recently_Played_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Played Artists.
        /// </summary>
        public static string Recently_Played_Artists {
            get {
                return ResourceManager.GetString("Recently_Played_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Rate.
        /// </summary>
        public static string RefreshRate {
            get {
                return ResourceManager.GetString("RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favorite.
        /// </summary>
        public static string Remove_From_Favorite {
            get {
                return ResourceManager.GetString("Remove_From_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Playlist.
        /// </summary>
        public static string Remove_From_Playlist {
            get {
                return ResourceManager.GetString("Remove_From_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reapeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme will be applied the next time you open the application..
        /// </summary>
        public static string Restart_App_To_Apply_Theme {
            get {
                return ResourceManager.GetString("Restart_App_To_Apply_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application to apply the change..
        /// </summary>
        public static string Restart_To_Apply_Msg {
            get {
                return ResourceManager.GetString("Restart_To_Apply_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Playlist.
        /// </summary>
        public static string Save_As_Playlist {
            get {
                return ResourceManager.GetString("Save_As_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks have been imported..
        /// </summary>
        public static string Scan_Done_Msg {
            get {
                return ResourceManager.GetString("Scan_Done_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan all Folders.
        /// </summary>
        public static string ScanFolder {
            get {
                return ResourceManager.GetString("ScanFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Image.
        /// </summary>
        public static string Select_an_Image {
            get {
                return ResourceManager.GetString("Select_an_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_View {
            get {
                return ResourceManager.GetString("Settings_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by.
        /// </summary>
        public static string SortedBy {
            get {
                return ResourceManager.GetString("SortedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish_Lang {
            get {
                return ResourceManager.GetString("Spanish_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting view has been changed to.
        /// </summary>
        public static string Starting_View_Changed_Msg {
            get {
                return ResourceManager.GetString("Starting_View_Changed_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting View.
        /// </summary>
        public static string Starting_View_Setting {
            get {
                return ResourceManager.GetString("Starting_View_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines wich view the application shows first..
        /// </summary>
        public static string Starting_View_Setting_Dscpt {
            get {
                return ResourceManager.GetString("Starting_View_Setting_Dscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Thickness.
        /// </summary>
        public static string StrokeThickness {
            get {
                return ResourceManager.GetString("StrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sub starting view for .
        /// </summary>
        public static string Sub_StartingView_Changed_Msg {
            get {
                return ResourceManager.GetString("Sub_StartingView_Changed_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The album.
        /// </summary>
        public static string The_Album {
            get {
                return ResourceManager.GetString("The_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artist.
        /// </summary>
        public static string The_Artist {
            get {
                return ResourceManager.GetString("The_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the queue.
        /// </summary>
        public static string The_Queue {
            get {
                return ResourceManager.GetString("The_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The track.
        /// </summary>
        public static string The_Track {
            get {
                return ResourceManager.GetString("The_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database.
        /// </summary>
        public static string TheDatabase {
            get {
                return ResourceManager.GetString("TheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data for.
        /// </summary>
        public static string TheDataFor {
            get {
                return ResourceManager.GetString("TheDataFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme has been changed to.
        /// </summary>
        public static string Theme_Changed_Msg {
            get {
                return ResourceManager.GetString("Theme_Changed_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Themes_Setting {
            get {
                return ResourceManager.GetString("Themes_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin.
        /// </summary>
        public static string Thin {
            get {
                return ResourceManager.GetString("Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string This_Month {
            get {
                return ResourceManager.GetString("This_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This_Year.
        /// </summary>
        public static string This_Year {
            get {
                return ResourceManager.GetString("This_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorow.
        /// </summary>
        public static string Tomorow {
            get {
                return ResourceManager.GetString("Tomorow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Info.
        /// </summary>
        public static string Track_Info_View {
            get {
                return ResourceManager.GetString("Track_Info_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track(s) not found and therefore deleted from the Database..
        /// </summary>
        public static string TrackNotFoundMsg {
            get {
                return ResourceManager.GetString("TrackNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Frequencies.
        /// </summary>
        public static string VCenterFreq {
            get {
                return ResourceManager.GetString("VCenterFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the objects composing the visualizer..
        /// </summary>
        public static string VColorDscpt {
            get {
                return ResourceManager.GetString("VColorDscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut High Frequencies.
        /// </summary>
        public static string VCutFreq {
            get {
                return ResourceManager.GetString("VCutFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Percentage.
        /// </summary>
        public static string VCutPercentage {
            get {
                return ResourceManager.GetString("VCutPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data quantity.
        /// </summary>
        public static string VDataQuantity {
            get {
                return ResourceManager.GetString("VDataQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        public static string VeryHigh {
            get {
                return ResourceManager.GetString("VeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the objects with the color..
        /// </summary>
        public static string VFillDscpt {
            get {
                return ResourceManager.GetString("VFillDscpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer.
        /// </summary>
        public static string Visualizer {
            get {
                return ResourceManager.GetString("Visualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer Settings.
        /// </summary>
        public static string VisualizerSettings {
            get {
                return ResourceManager.GetString("VisualizerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects Size.
        /// </summary>
        public static string VObjectLength {
            get {
                return ResourceManager.GetString("VObjectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data representation.
        /// </summary>
        public static string VRepresentation {
            get {
                return ResourceManager.GetString("VRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth Graph.
        /// </summary>
        public static string VSmoothGraph {
            get {
                return ResourceManager.GetString("VSmoothGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thickness of the border of the objects, or the thickness of the line for the graphs representations..
        /// </summary>
        public static string VStrokeThickness {
            get {
                return ResourceManager.GetString("VStrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string Welcome_Back {
            get {
                return ResourceManager.GetString("Welcome_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Interactions.
        /// </summary>
        public static string Your_Interactions {
            get {
                return ResourceManager.GetString("Your_Interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating, Favorite, PlayCount....
        /// </summary>
        public static string Your_Interactions_Dscpt {
            get {
                return ResourceManager.GetString("Your_Interactions_Dscpt", resourceCulture);
            }
        }
    }
}
